#!/usr/bin/env python3
"""
Generate standalone HTML with embedded dependency graph and paranoia report data.

This creates a single self-contained HTML file that can be shared or hosted
without requiring users to manually load JSON files.

Usage:
    python scripts/embed_data.py \
        --viewer viewer/paranoia-viewer.html \
        --depgraph depgraph.json \
        --report paranoia_report.json \
        --output standalone.html
"""

import argparse
import json
import sys
from pathlib import Path


def embed_data(viewer_path: Path, depgraph_path: Path, report_path: Path, output_path: Path):
    """
    Create standalone HTML by embedding JSON data into the viewer.
    """
    # Read the viewer HTML
    viewer_html = viewer_path.read_text()
    
    # Read JSON data
    depgraph_data = depgraph_path.read_text() if depgraph_path.exists() else "null"
    report_data = report_path.read_text() if report_path.exists() else "null"
    
    # Create embedded data script
    embedded_script = f"""
    <script>
        // Embedded data - generated by embed_data.py
        window.EMBEDDED_DEPGRAPH = {depgraph_data};
        window.EMBEDDED_REPORT = {report_data};
        
        // Auto-load embedded data on page load
        document.addEventListener('DOMContentLoaded', function() {{
            if (window.EMBEDDED_DEPGRAPH) {{
                console.log('Loading embedded dependency graph...');
                graphData = window.EMBEDDED_DEPGRAPH;
            }}
            if (window.EMBEDDED_REPORT) {{
                console.log('Loading embedded paranoia report...');
                reportData = window.EMBEDDED_REPORT;
            }}
            if (window.EMBEDDED_DEPGRAPH) {{
                updateView();
            }}
        }});
    </script>
    """
    
    # Insert embedded data script before closing </body> tag
    if '</body>' in viewer_html:
        output_html = viewer_html.replace('</body>', f'{embedded_script}\n</body>')
    else:
        output_html = viewer_html + embedded_script
    
    # Add notice at the top
    notice = """<!--
    Standalone LeanDepViz Report
    Generated with embedded dependency graph and verification results.
    
    This file is self-contained and can be opened directly in a browser
    or hosted on any static file server (GitHub Pages, Vercel, Netlify, etc.)
    
    No backend required - all processing happens client-side.
-->
"""
    output_html = notice + output_html
    
    # Write output
    output_path.write_text(output_html)
    print(f"✓ Created standalone HTML: {output_path}")
    print(f"  - Embedded dependency graph: {depgraph_path}")
    if report_path.exists():
        print(f"  - Embedded paranoia report: {report_path}")
    else:
        print(f"  - No paranoia report (file not found)")
    print(f"\nYou can now:")
    print(f"  1. Open locally: open {output_path}")
    print(f"  2. Share the file directly")
    print(f"  3. Host on GitHub Pages, Vercel, Netlify, etc.")


def main():
    parser = argparse.ArgumentParser(
        description="Generate standalone HTML with embedded data"
    )
    parser.add_argument(
        "--viewer",
        default="viewer/paranoia-viewer.html",
        help="Path to the viewer HTML template"
    )
    parser.add_argument(
        "--depgraph",
        required=True,
        help="Path to dependency graph JSON file"
    )
    parser.add_argument(
        "--report",
        default="paranoia_report.json",
        help="Path to paranoia report JSON file (optional)"
    )
    parser.add_argument(
        "--output",
        default="standalone-report.html",
        help="Output path for standalone HTML file"
    )
    
    args = parser.parse_args()
    
    # Convert to Path objects
    viewer_path = Path(args.viewer)
    depgraph_path = Path(args.depgraph)
    report_path = Path(args.report)
    output_path = Path(args.output)
    
    # Check inputs exist
    if not viewer_path.exists():
        print(f"Error: Viewer not found: {viewer_path}", file=sys.stderr)
        sys.exit(1)
    
    if not depgraph_path.exists():
        print(f"Error: Dependency graph not found: {depgraph_path}", file=sys.stderr)
        sys.exit(1)
    
    # Generate standalone HTML
    embed_data(viewer_path, depgraph_path, report_path, output_path)


if __name__ == "__main__":
    main()
